---
title: "Group Project 2"
author: "Luke Werkmeister-Martin"
date: "February 23, 2023"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

df <- read_csv("https://raw.githubusercontent.com/bobbyjy/599Project2/main/project2data.csv")

library(tidyverse)
library(skimr)
library(survival)
library(survminer)
library(fitdistrplus)
```

##Feature Engineering
```{r}
df <- df%>%
  mutate(atbats = vatbats + hatbats,
         hits = vhit + hhit,
         rbi = vrbi + hrbi,
         walks = vwalk + hwalk,
         strikeouts = vstrkout + hstrkout
         )%>%
  dplyr::select(-vatbats, -hatbats, -vhit, -hhit, -vrbi, -hrbi, -vwalk, -hwalk, -vstrkout, -hstrkout)
```

```{r}
df$atbat_bin <- as.factor(cut_number(df$atbats,3))
df$hit_bin <- as.factor(cut_number(df$hits,3))
df$rbi_bin <- as.factor(cut_number(df$rbi,3))
df$walks_bin <- as.factor(cut_number(df$walks,3))
df$SO_bin <- as.factor(cut_number(df$strikeouts,3))

df <- df%>%
  dplyr::select(-atbats, -hits, -rbi, -walks, -strikeouts)

df <- df%>%
  mutate(left = length,
         right = length)
```


##Kaplan Meier EDA
```{r}
survObject <- Surv(df$left,df$right,type="interval2")
km=survfit(survObject~df$hleague)

ggsurvplot(fit=km, data=df,risk.table = F,conf.int=T)
```




